ALTER TABLE dbo.Usuarios
DROP CONSTRAINT CKUsuariosEstado;

GO

ALTER TABLE dbo.Usuarios
ADD CONSTRAINT CKUsuariosEstado
CHECK (Estado IN ('PENDIENTEVERIFICACION', 'ACTIVO', 'BLOQUEADO', 'DESHABILITADO', 'ELIMINADO'));
